THE GREAT REFACTOR: version 2 of dotfiles
So, I realized that creating the init and alias scripts for each of my tools was exactly what the oh-my-zsh plugins did. Damn, all that work for nothing. Take this as a lesson, read the fucking docs. Anywho, so I got rid of all that jazz in favour of oh-my-zsh plugins (much cleaner setup). aliases are now all in ~/.aliases, env vars/path modication have been aggregated to ~/.init, and the init stuff for zsh/bash have just been placed inside their respective rc files. Now, this does mean none of my tools like pyenv will be avaliable for, bash, but I'll never not have zsh, so why use bash at all? In any case, even if zsh isn't installed, I can always just get a binary version (no sudo priveleges needed). I'll cross that bridge when it comes. I have no idea why I typed this all out, I'm literally talking to no one.

diff --git a/bin/github-sshkey b/bin/github-sshkey
--- a/bin/github-sshkey
+++ b/bin/github-sshkey
@@ -1,16 +1,18 @@
 #!/bin/bash
 
-if [ ! -f "$HOME/.ssh/id_rsa.pub" ]; then
-    echo "public key was not found at $HOME/.ssh/id_rsa.pub"
-    echo "please generate one with:"
-    echo "ssh-keygen -t rsa -b 4096"
-    exit 1
-fi
+echo "github removed api authentication via username/password, gonna need to make a workaround :("
 
-printf "Enter github username: $hostname"
-read username
+# if [ ! -f "$HOME/.ssh/id_rsa.pub" ]; then
+#     echo "public key was not found at $HOME/.ssh/id_rsa.pub"
+#     echo "please generate one with:"
+#     echo "ssh-keygen -t rsa -b 4096"
+#     exit 1
+# fi
 
-title="$(whoami)@$(hostname)"
-pub_key=$(cat "$HOME/.ssh/id_rsa.pub")
+# printf "Enter github username: $hostname"
+# read username
 
-curl -u "$username" --data "{\"title\":\"$title\",\"key\":\"$pub_key\"}" https://api.github.com/user/keys
+# title="$(whoami)@$(hostname)"
+# pub_key=$(cat "$HOME/.ssh/id_rsa.pub")
+
+# curl -u "$username" --data "{\"title\":\"$title\",\"key\":\"$pub_key\"}" https://api.github.com/user/keys
diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -1,35 +1,44 @@
 #!/usr/bin/env bash
 
-#!/bin/bash
-if [[ $EUID -ne 0 ]]; then
-   echo "This script must be run as root or with root priveleges (via sudo)"
-   exit 1
-fi
+## TODO: finish bootstrap script, which should:
+# - ask for install location and clone the repo to that correct location
+# - run install script for the given os (if linux ask for installation type (ie sudo vs no sudo, os type, etc ...)
+# - ask options for which setup scripts to run (ie zsh, vscode) and run them
+# - run dotfiles symlinking
 
-# exit script if a command fails
-set -e
 
-# dotfiles root dir environment variable
-export DOTFILES_ROOT=${HOME}/.dotfiles
-[[ -a ${HOME}/.localrc ]] && source ${HOME}/.localrc &> /dev/null
-[ ! -d "$DOTFILES_ROOT" ] && echo "ERROR: dotfiles root directory ($DOTFILES_ROOT) was not found." && return
 
-cd ${DOTFILES_ROOT}
+# # exit script if a command fails
+# set -e
 
-# check os and install accordingly
-if test "$(uname)" = "Darwin"; then
-    sh macos/install.sh
-elif test "$(uname)" = "Linux"; then
-    sh linux/install.sh
-else
-    echo "os must be darwin (macos) or linux"
-    exit 1
-fi
 
-# run setup.sh files
-for file in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name 'setup.sh' -not -path '*.git*'); do
-    sh $file
-done
+# # check for root priveleges
+# if [[ $(id -u) -ne 0 ]] ; then
+#     echo "Please run as root or with root priveleges"
+#     exit 1
+# fi
 
-# symlink dotfiles
-./dotfiles
+# # dotfiles root path
+# export DOTFILES_ROOT=${HOME}/.dotfiles
+# [[ -a ${HOME}/.localrc ]] && source ${HOME}/.localrc &> /dev/null
+# [ ! -d "$DOTFILES_ROOT" ] && echo "ERROR: dotfiles root directory ($DOTFILES_ROOT) was not found." && return
+
+# cd ${DOTFILES_ROOT}
+
+# # check os and install accordingly
+# if test "$(uname)" = "Darwin"; then
+#     sh macos/install.sh
+# elif test "$(uname)" = "Linux"; then
+#     sh linux/install.sh
+# else
+#     echo "os must be darwin (macos) or linux"
+#     exit 1
+# fi
+
+# # run setup.sh files
+# for file in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name 'setup.sh' -not -path '*.git*'); do
+#     sh $file
+# done
+
+# # symlink dotfiles
+# ./dotfiles
